name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "CMakePresets.json"
      - "cmake/libraries.json"
      - "!cmake/intel.cmake"
      - "!cmake/cray.cmake"
      - ".github/workflows/ci.yml"
      - "!docs/**"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gcc-new:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        hwm14: [false]
        os: [ubuntu-24.04]
        gcc: [12, 13, 14]

    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
      FC: gfortran-${{ matrix.gcc }}
      CMAKE: cmake
      CTEST: ctest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-pkg
    - uses: ./.github/workflows/composite-linux


  cmake-320:
    timeout-minutes: 30

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        cmake_version: ["3.20.6"]
        gcc: [12]

    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
      FC: gfortran-${{ matrix.gcc }}

    steps:

    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-pkg

    - name: Install GCC-${{ matrix.gcc }}
      timeout-minutes: 15
      run: sudo apt install gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }} gfortran-${{ matrix.gcc }}

    - uses: ./.github/workflows/composite-cmake
    - uses: ./.github/workflows/composite-linux


  gcc-old:
    timeout-minutes: 30

    strategy:
      matrix:
        hwm14: [false]
        os: [ubuntu-22.04]
        gcc: [9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
      FC: gfortran-${{ matrix.gcc }}
      CMAKE: cmake
      CTEST: ctest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-pkg
    - uses: ./.github/workflows/composite-linux
